{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "f9def34c-eeaf-4e55-93f2-beeab0b61c4a",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "🎯 All models saved successfully in /models folder!\n",
      "\n",
      "📂 Models loaded successfully!\n",
      "\n",
      "🎬 Hybrid Recommendation:\n",
      "                                               title  \\\n",
      "1706                                     Antz (1998)   \n",
      "2355                              Toy Story 2 (1999)   \n",
      "2809  Adventures of Rocky and Bullwinkle, The (2000)   \n",
      "3000                Emperor's New Groove, The (2000)   \n",
      "3568                           Monsters, Inc. (2001)   \n",
      "\n",
      "                                           genres  \n",
      "1706  Adventure|Animation|Children|Comedy|Fantasy  \n",
      "2355  Adventure|Animation|Children|Comedy|Fantasy  \n",
      "2809  Adventure|Animation|Children|Comedy|Fantasy  \n",
      "3000  Adventure|Animation|Children|Comedy|Fantasy  \n",
      "3568  Adventure|Animation|Children|Comedy|Fantasy  \n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import joblib\n",
    "import os\n",
    "from sklearn.metrics.pairwise import cosine_similarity\n",
    "from sklearn.feature_extraction.text import TfidfVectorizer\n",
    "from sklearn.neighbors import NearestNeighbors\n",
    "\n",
    "# =======================\n",
    "# 1. Load and Preprocess\n",
    "# =======================\n",
    "\n",
    "def load_data(movies_path, ratings_path):\n",
    "    movies = pd.read_csv(movies_path)\n",
    "    ratings = pd.read_csv(ratings_path)\n",
    "    return movies, ratings\n",
    "\n",
    "def preprocess_movies(movies):\n",
    "    movies['genres'] = movies['genres'].fillna('')\n",
    "    movies['genre_tokens'] = movies['genres'].str.replace('|', ' ')\n",
    "    return movies\n",
    "\n",
    "# =========================\n",
    "# 2. Content-Based Modeling\n",
    "# =========================\n",
    "\n",
    "def build_content_model(movies):\n",
    "    tfidf = TfidfVectorizer(stop_words='english')\n",
    "    tfidf_matrix = tfidf.fit_transform(movies['genre_tokens'])\n",
    "    cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)\n",
    "    movie_index = pd.Series(movies.index, index=movies['title'])\n",
    "    return cosine_sim, movie_index\n",
    "\n",
    "# =========================\n",
    "# 3. Collaborative Filtering (KNN)\n",
    "# =========================\n",
    "\n",
    "def build_knn_model(ratings):\n",
    "    rating_matrix = ratings.pivot_table(index='userId',\n",
    "                                        columns='movieId',\n",
    "                                        values='rating').fillna(0)\n",
    "    model_knn = NearestNeighbors(metric='cosine', algorithm='brute')\n",
    "    model_knn.fit(rating_matrix)\n",
    "    return model_knn, rating_matrix\n",
    "\n",
    "# =========================\n",
    "# 4. Save & Load Models\n",
    "# =========================\n",
    "\n",
    "def save_models(model_knn, rating_matrix, movies, cosine_sim, movie_index):\n",
    "    os.makedirs(\"models\", exist_ok=True)\n",
    "    joblib.dump(model_knn, \"models/knn_model.pkl\")\n",
    "    joblib.dump(rating_matrix, \"models/rating_matrix.pkl\")\n",
    "    joblib.dump(movie_index, \"models/movie_index.pkl\")\n",
    "    joblib.dump(movies, \"models/movies.pkl\")\n",
    "    np.save(\"models/cosine_sim.npy\", cosine_sim)\n",
    "    print(\"\\n🎯 All models saved successfully in /models folder!\")\n",
    "\n",
    "def load_models():\n",
    "    model_knn = joblib.load(\"models/knn_model.pkl\")\n",
    "    rating_matrix = joblib.load(\"models/rating_matrix.pkl\")\n",
    "    movie_index = joblib.load(\"models/movie_index.pkl\")\n",
    "    movies = joblib.load(\"models/movies.pkl\")\n",
    "    cosine_sim = np.load(\"models/cosine_sim.npy\")\n",
    "    print(\"\\n📂 Models loaded successfully!\")\n",
    "    return model_knn, rating_matrix, movies, cosine_sim, movie_index\n",
    "\n",
    "# =========================\n",
    "# 5. Recommendation Functions\n",
    "# =========================\n",
    "\n",
    "def content_recommend(title, movies, cosine_sim, movie_index, n=5):\n",
    "    idx = movie_index[title]\n",
    "    sim_scores = list(enumerate(cosine_sim[idx]))\n",
    "    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)[1:n+1]\n",
    "    movie_indices = [i[0] for i in sim_scores]\n",
    "    return movies[['title', 'genres']].iloc[movie_indices]\n",
    "\n",
    "def collaborative_recommend(user_id, model_knn, rating_matrix, movies, n=5):\n",
    "    user_index = rating_matrix.index.get_loc(user_id)\n",
    "    distances, indices = model_knn.kneighbors(\n",
    "        rating_matrix.iloc[user_index, :].values.reshape(1, -1),\n",
    "        n_neighbors=n+1)\n",
    "    similar_users = indices.flatten()[1:]\n",
    "    rec_scores = rating_matrix.iloc[similar_users].mean(axis=0).sort_values(ascending=False).head(n)\n",
    "    return movies[movies['movieId'].isin(rec_scores.index)][['title', 'genres']]\n",
    "\n",
    "def hybrid_recommend(user_id, liked_movie, movies, cosine_sim, movie_index, model_knn, rating_matrix, n=5):\n",
    "    content_rec = content_recommend(liked_movie, movies, cosine_sim, movie_index, n)\n",
    "    collab_rec = collaborative_recommend(user_id, model_knn, rating_matrix, movies, n)\n",
    "    hybrid = pd.concat([content_rec, collab_rec]).drop_duplicates().head(n)\n",
    "    return hybrid\n",
    "\n",
    "# =========================\n",
    "# 6. Run / Train / Load Test\n",
    "# =========================\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    MOVIES_PATH = \"C:/Users/siril/Docs/codectechnologies/CodecTech Project/movie-recommender/data/movies.csv\"\n",
    "    RATINGS_PATH = \"C:/Users/siril/Docs/codectechnologies/CodecTech Project/movie-recommender/data/ratings.csv\"\n",
    "\n",
    "    movies, ratings = load_data(MOVIES_PATH, RATINGS_PATH)\n",
    "    movies = preprocess_movies(movies)\n",
    "\n",
    "    cosine_sim, movie_index = build_content_model(movies)\n",
    "    model_knn, rating_matrix = build_knn_model(ratings)\n",
    "\n",
    "    save_models(model_knn, rating_matrix, movies, cosine_sim, movie_index)\n",
    "\n",
    "    model_knn, rating_matrix, movies, cosine_sim, movie_index = load_models()\n",
    "\n",
    "    print(\"\\n🎬 Hybrid Recommendation:\")\n",
    "    print(hybrid_recommend(1, \"Toy Story (1995)\", movies, cosine_sim, movie_index, model_knn, rating_matrix, 5))\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3a73b25a-d4ef-4b4e-bcdb-4400123dc2b7",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
